### ISSUE TITLE
Facebook Sample License

### ISSUE THREAD

**Issue by quilmach** [clips/pattern#103]
Sorry if this is a dumb question. I am trying the Facebook example and tried the following in the license assignment: User Token, App Token, App Id, Appsecret and in all cases I get a  pattern.web.HTTP401Authentication error. What should I be assigning to license?
Note that I was able to get pass obtaining my profile as per example. I know now that the User Token should be working but I still get an authentication error while searching for NEWS as in the example. Never mind anyway, I was able to access examples from the Mining the Social Web book and I will be using those libraries.

**Comment by markus-beuckelmann** [comment]
Moved to #181.
