### ISSUE TITLE
Verb missing in "verbs", but available via tenses(verb) & lexeme(verb)

### ISSUE THREAD

**Issue by gambolputty** [clips/pattern#121]
Hello,

I wonder why the german verb "skandieren" is not available in "pattern.de verbs", but in tenses("skandieren") and lexeme("skandieren").

See:
`>>> print "skandieren" in verbs`
`False`

`>>> tenses("skandieren")`
`[('infinitive', None, None, None, None), ('present', 1, 'plural', 'imperative', 'imperfective'), ('present', 1, 'plural', 'indicative', 'imperfective'), ('present', 1, 'plural', 'subjunctive', 'imperfective'), ('present', 3, 'plural', 'indicative', 'imperfective'), ('present', 3, 'plural', 'subjunctive', 'imperfective')]`

`>>> lexeme("skandieren")`
`['skandieren', 'skandiere', 'skandierst', 'skandiert', 'skandierend', u'skandierte', u'skandiertest', u'skandierten', u'skandiertet', u'skandierest', u'skandieret']`

Can anyone explain this to me?

Gregor

**Comment by gambolputty** [comment]
Sorry, I got the concept of how pattern manages this totally wrong at the beginning.

**Comment by nadavb** [comment]
Can you explain the solution to your question?
