### ISSUE TITLE
Implementing "total" property of SearchEngine.search()

### ISSUE THREAD

**Issue by shawnanctil** [clips/pattern#159]
I'm a humanist/historian, and not a programmer, so forgive me if my question is beginner-level.

I'm trying to write a script that returns the total number of results for any given query. I've seen other scripts that can do something similar from the command line using the argparse module, but my search brought me back to pattern. I've had some success in writing search scripts with pattern.web to date and would prefer to use it if I can do so simply.

Here's what I have for a script so far as well as where I've been trying to input some variation of a "total" property:

```

from datetime import date
from pattern.web import Google

engine = Google(license=None)
today = date.today()

with open('kwords.txt', 'r') as inFile:
    with open('kwordsGHits.txt', 'a+') as outFile:
        keywords = inFile.readlines()
        outFile.write('Search results compiled on: ' + str(today) + '\n\n')
        total = engine.search(results) # I've tried a few different combinations here. No luck.
        for keyword in keywords:
            for result in engine.search(keyword, cached=False):
                outFile.write(str(keyword) + ',' + '') #Here's where I want to add the "total" results
                outFile.write('\n')
            outFile.close()
```

Any guidance you can offer would be appreciated.

**Comment by antavelos** [comment]
Hi @shawnanctil 

I see that there is already a total property on the returned object by the search function. You could use something like that:
```
from datetime import date
from pattern.web import Google

engine = Google(license=None)
today = date.today()

with open('kwords.txt', 'r') as inFile:
    with open('kwordsGHits.txt', 'a+') as outFile:
        keywords = inFile.readlines()
        outFile.write('Search results compiled on: ' + str(today) + '\n\n')
        for keyword in keywords:
            result = engine.search(keyword, cached=False)
            outFile.write("{},{}\n".format(keyword.strip(), result.total))
            outFile.write("\n")
```

I hope that helps.

**Comment by shawnanctil** [comment]
Sorry for the delay @antavelos. Thank you. This helps a lot!
