### ISSUE TITLE
Issues with SLP model and POS tagging (pattern.en)

### ISSUE THREAD

**Issue by markus-beuckelmann** [clips/pattern#182]
There are currently some issues with POS misclassification in `pattern.en` on Python 2.7 which cause multiple tests in `test_en.py` and `test_text.py` to fail.  Let's take a look at `test_tag()` for instance (see [Travis log](https://travis-ci.org/clips/pattern/jobs/241813303#L1295)), which looks like this:
```python
# Assert [("black", "JJ"), ("cats", "NNS")].
v = en.tag("black cats")
self.assertEqual(v, [("black", "JJ"), ("cats", "NNS")])
```

The test fails because 'black' get classified as `JJS` (adjective, superlative) instead of `JJ` (adjective). 

Here is what happens: When we call `en.tag()` it gets passed down to `en.parse()` which will then be handled by `parse()` in `text/__init__.py` ([source](https://github.com/clips/pattern/blob/master/pattern/text/__init__.py#L854)) which in turn calls `find_tags()` ([source](https://github.com/clips/pattern/blob/master/pattern/text/__init__.py#L1195)).  Inside `find_tags()` the word gets looked up in the lexicon ([here](https://github.com/clips/pattern/blob/master/pattern/text/__init__.py#L1210)) which assigns the correct (!) label `JJ`. Then, this label is overruled ([here](https://github.com/clips/pattern/blob/master/pattern/text/__init__.py#L1218)) by the model (because 'black' is listed in `model.unkown`) and `classify()` ([source](https://github.com/clips/pattern/blob/master/pattern/text/__init__.py#L424)) returns the wrong label 'JJS'.

There are many similar examples that you can look at: [`test_parse`](https://travis-ci.org/clips/pattern/jobs/241813303#L1279) (see e.g. misclassification for 'sat'),  [`test_find_tags`](https://travis-ci.org/clips/pattern/jobs/241813303#L1265), [`test_tagged_string`](https://travis-ci.org/clips/pattern/jobs/241813303#L1315), [`test_word`](https://travis-ci.org/clips/pattern/jobs/241813303#L1334), [`test_document`](https://travis-ci.org/clips/pattern/jobs/241813303#L1434).

Sure, the SLP model is a statistical model and consequently is allowed to be wrong in some cases, but what bothers me is that it apparently used to work some time ago. Sentences of the form "The black cat sat on..." are scattered everywhere across unit tests that I can't believe that the model got that wrong all the time.

I just can't find the cause for this change. @tom-de-smedt, what am I missing?

**Comment by markus-beuckelmann** [comment]
I finally narrowed down the cause for this problem. Looks like [this](https://github.com/clips/pattern/commit/dc855341aadea1ed56413bb2c1d8f611ff714a48#diff-47929eb18e31dd1daf081c30fbb18cdcR435) line in `pattern/text/__init__.py` introduced in https://github.com/clips/pattern/commit/dc855341aadea1ed56413bb2c1d8f611ff714a48 is responsible for the problems mentioned above.

**Comment by piyush0609** [comment]
@markus-beuckelmann I would be glad to work on the issue and try to resolve it, if you are not already working it.

**Comment by markus-beuckelmann** [comment]
@piyush0609, it is already fixed as of https://github.com/clips/pattern/commit/93235fe6a554a247d97752204bfc3f7ade11a281. It's great that you want to contribute though, keep an eye out for issues tagged with the "help" label.
