### ISSUE TITLE
NameError : name 'unicode' is not defined

### ISSUE THREAD

**Issue by ckshitij** [clips/pattern#184]
In /Pattern-2.6-py3.5.egg/pattern/text/tree.py

->14436 class TaggedString(unicode):

->.. NameError : name 'unicode' is not defined

**Comment by markus-beuckelmann** [comment]
@ckshitij: The current version of Pattern is Python 2 only. We are working towards a Python 3 version on the python3 branch in this repository (see issue #62).

**Comment by ckshitij** [comment]
Ok but Actually i m using gensim library for lemmitization and its need pattern only . It won't work for Pattern3.
