### ISSUE TITLE
wordnet.py Tabs error Inconsistent tabs and spaces

### ISSUE THREAD

**Issue by xenu256** [clips/pattern#188]
When doing #187 187
found that
pattern/text/en/wordnet/pywordnet/wordnet.py

file (maybe more) is damaged:

```text
Sorry: TabError: inconsistent use of tabs and spaces in indentation
```
I'd suggest using Python linters before accepting any PRs as correcting such errors by hand would be nightmare.

**Comment by markus-beuckelmann** [comment]
`pywordnet` is deprecated and has been absorbed into `nltk`. We are refactoring the code to make use of the new interface and will then completely remove `pywordnet` from Pattern.

**Comment by xenu256** [comment]
Cool, great to know!
