### ISSUE TITLE
Error importing pattern3.en

### ISSUE THREAD

**Issue by JanmajaySingh** [clips/pattern#217]
While trying to import pattern3.en, the compiler throws generic indentation error in pattern3.text.tree.py.

Here is the traceback:

    >>> import pattern3.en
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/singh/anaconda/envs/venv123/lib/python3.6/site-  packages/pattern3/text/en/__init__.py", line 22, in <module>
        from pattern3.text import (
      File "/Users/singh/anaconda/envs/venv123/lib/python3.6/site-packages/pattern3/text/__init__.py", line 28, in <module>
        from pattern3.text.tree import Tree, Text, Sentence, Slice, Chunk, PNPChunk, Chink, Word, table
      File "/Users/singh/anaconda/envs/venv123/lib/python3.6/site-packages/pattern3/text/tree.py", line 37
        except:
             ^
    IndentationError: expected an indented block

**Comment by JanmajaySingh** [comment]
For anyone else facing the same issue, @markus-beuckelmann's comment on issue #62 is the solution.
Currently pattern3 hosted on PyPI is deprecated.
Using the development branch (with python 3 support) solves the problem.
It can be cloned by `git clone -b development https://github.com/clips/pattern` and installed using `pip` or `conda` .
Thank you @markus-beuckelmann .

**Comment by jt4000** [comment]
> For anyone else facing the same issue, @markus-beuckelmann's comment on issue #62 is the solution.
> Currently pattern3 hosted on PyPI is deprecated.
> Using the development branch (with python 3 support) solves the problem.
> It can be cloned by `git clone -b development https://github.com/clips/pattern` and installed using `pip` or `conda` .
> Thank you @markus-beuckelmann .



> For anyone else facing the same issue, @markus-beuckelmann's comment on issue #62 is the solution.
> Currently pattern3 hosted on PyPI is deprecated.
> Using the development branch (with python 3 support) solves the problem.
> It can be cloned by `git clone -b development https://github.com/clips/pattern` and installed using `pip` or `conda` .
> Thank you @markus-beuckelmann .

How should it be working if you use anaconda

**Comment by rahulraj987** [comment]
when I follow the above solution I am getting another set of error. related to mysql 

ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pp/5_z3l23d2rxc2y9274mb2cwh0000gn/T/pip-install-v5curwlr/mysqlclient/setup.py'"'"'; __file__='"'"'/private/var/folders/pp/5_z3l23d2rxc2y9274mb2cwh0000gn/T/pip-install-v5curwlr/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/pp/5_z3l23d2rxc2y9274mb2cwh0000gn/T/pip-record-1td1v1mv/install-record.txt --single-version-externally-managed --compile --user --prefix=
         cwd: /private/var/folders/pp/5_z3l23d2rxc2y9274mb2cwh0000gn/T/pip-install-v5curwlr/mysqlclient/
    Complete output (30 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.8
    creating build/lib.macosx-10.9-x86_64-3.8/MySQLdb
    copying MySQLdb/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/MySQLdb
    copying MySQLdb/_exceptions.py -> build/lib.macosx-10.9-x86_64-3.8/MySQLdb
    copying MySQLdb/compat.py -> build/lib.macosx-10.9-x86_64-3.8/MySQLdb
    copying MySQLdb/connections.py -> build/lib.macosx-10.9-x86_64-3.8/MySQLdb
    copying MySQLdb/converters.py -> build/lib.macosx-10.9-x86_64-3.8/MySQLdb
    copying MySQLdb/cursors.py -> build/lib.macosx-10.9-x86_64-3.8/MySQLdb
    copying MySQLdb/release.py -> build/lib.macosx-10.9-x86_64-3.8/MySQLdb
    copying MySQLdb/times.py -> build/lib.macosx-10.9-x86_64-3.8/MySQLdb
    creating build/lib.macosx-10.9-x86_64-3.8/MySQLdb/constants
    copying MySQLdb/constants/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/MySQLdb/constants
    copying MySQLdb/constants/CLIENT.py -> build/lib.macosx-10.9-x86_64-3.8/MySQLdb/constants
    copying MySQLdb/constants/CR.py -> build/lib.macosx-10.9-x86_64-3.8/MySQLdb/constants
    copying MySQLdb/constants/ER.py -> build/lib.macosx-10.9-x86_64-3.8/MySQLdb/constants
    copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.macosx-10.9-x86_64-3.8/MySQLdb/constants
    copying MySQLdb/constants/FLAG.py -> build/lib.macosx-10.9-x86_64-3.8/MySQLdb/constants
    running build_ext
    building 'MySQLdb._mysql' extension
    creating build/temp.macosx-10.9-x86_64-3.8
    creating build/temp.macosx-10.9-x86_64-3.8/MySQLdb
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -Dversion_info=(1,4,6,'final',0) -D__version__=1.4.6 -I/usr/local/Cellar/mysql/8.0.18_1/include/mysql -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c MySQLdb/_mysql.c -o build/temp.macosx-10.9-x86_64-3.8/MySQLdb/_mysql.o
    gcc -bundle -undefined dynamic_lookup -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.8/MySQLdb/_mysql.o -L/usr/local/Cellar/mysql/8.0.18_1/lib -lmysqlclient -lssl -lcrypto -o build/lib.macosx-10.9-x86_64-3.8/MySQLdb/_mysql.cpython-38-darwin.so
    ld: library not found for -lssl
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pp/5_z3l23d2rxc2y9274mb2cwh0000gn/T/pip-install-v5curwlr/mysqlclient/setup.py'"'"'; __file__='"'"'/private/var/folders/pp/5_z3l23d2rxc2y9274mb2cwh0000gn/T/pip-install-v5curwlr/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/pp/5_z3l23d2rxc2y9274mb2cwh0000gn/T/pip-record-1td1v1mv/install-record.txt --single-version-externally-managed --compile --user --prefix= Check the logs for full command output.
