### ISSUE TITLE
Provide Indonesian Language Support

### ISSUE THREAD

**Issue by probeadd** [clips/pattern#219]
Hi! I am Satrio and I'm interested to contribute to this project. I want Pattern support my language, Bahasa Indonesia. Would you provide any guide on how to add language support to Pattern? Assume that I have part-of-speech tagged corpus of Bahasa Indonesia. Thank you!

@tom-de-smedt @markus-beuckelmann

**Comment by jayvdb** [comment]
https://github.com/clips/pattern/tree/development/pattern/text
