### ISSUE TITLE
lemma bug for some words end with 's'

### ISSUE THREAD

**Issue by Steven-AA** [clips/pattern#221]
![image](https://user-images.githubusercontent.com/22387129/37512906-598781c4-293e-11e8-8e6a-8064134af68b.png)

![image](https://user-images.githubusercontent.com/22387129/37513120-0dfb5cd4-293f-11e8-9072-4371da4b495e.png)

**Comment by Lguyogiro** [comment]
`lemma` is specifically meant to return the base form of Verbs. Since these words aren't Verbs, they are treated as unseen Verbs, and undergo the default lemmatization. See https://www.clips.uantwerpen.be/pages/pattern-en#conjugation

**Comment by Steven-AA** [comment]
thanks a lot

BTW, is there a easy way to get the base form of any word?

**Comment by Lguyogiro** [comment]
I don't think so. You can use `lemma` for getting the base form of a verb, and `singularize` to get the singular form of a Noun (https://www.clips.uantwerpen.be/pages/pattern-en#pluralization)...

**Comment by Steven-AA** [comment]
Thanks.
