### ISSUE TITLE
how to add chinese support?

### ISSUE THREAD

**Issue by dreampuf** [clips/pattern#23]

**Comment by hsukevin** [comment]
bump

**Comment by eromoe** [comment]
I there is Chinese list in  http://www.clips.ua.ac.be/pages/pattern-dev 

Language | Code | Speakers | Example countries
-- | -- | -- | --
Mandarin | cmn | 955M | China + Taiwan (945), Singapore (3)
Spanish | es | 350M | Argentina (40), Colombia (40), Mexico (100), Spain (45)
English | en | 340M | Canada (30), United Kingdom (60), United States (300)
German | de | 100M | Austria (10), Germany (80), Switzerland (7)
French | fr | 70M | France (65), Côte d'Ivoire (20)
Italian | it | 60M | Italy (60)
Dutch | nl | 27M | The Netherlands (25), Belgium (6), Suriname (1)

How do I use that ?
