### ISSUE TITLE
Update Python 3 support description on Uni Antwerp homepage 

### ISSUE THREAD

**Issue by bact** [clips/pattern#244]
Pattern homepage at Uni Antwerp https://www.clips.uantwerpen.be/pattern
still says "Pattern is written for Python 2.5+ (no support for Python 3 yet)."

This gives wrong information (Pattern is now supports Python 2.7 and Python 3.6) and may make some people give up on trying.

**Comment by tuxayo** [comment]
Python 3 support isn't stable yet: https://github.com/clips/pattern/issues/62#issuecomment-397685541
It's only in the development version (master branch)

**Comment by bact** [comment]
I see. Thanks a lot for clarification.

**Comment by cursed4ever** [comment]
Please close this issue
